name: Master CI Build

on: 
  push:
    branches:
      - gha-master-ci-pa

env:
  APP_NAME: interface
  BUILD_TYPE: Release
  BUILD_NUMBER: ${{ github.run_number }}
  BUCKET_NAME: athena-public
  CI_BUILD: Github
  # CMAKE_BACKTRACE_URL: https://highfidelity.sp.backtrace.io:6098
  # CMAKE_BACKTRACE_TOKEN: ${{ secrets.backtrace_token }}
  # CMAKE_BACKTRACE_SYMBOLS_TOKEN: ${{ secrets.backtrace_symbols_token }}
  GIT_COMMIT: ${{ github.sha }}
  # VCPKG did not build well on OSX disabling HIFI_VCPKG_BOOTSTRAP, which invokes a download to a working version of vcpkg
  # HIFI_VCPKG_BOOTSTRAP: true
  LAUNCHER_HMAC_SECRET: ${{ secrets.launcher_hmac_secret }}
  OCULUS_APP_ID: '${{ secrets.oculus_app_id }}'
  RELEASE_TYPE: PRODUCTION
  RELEASE_NUMBER: ${{ github.run_number }}
  RELEASE_DYNAMODB_V2: ReleaseManager2-ReleaseQueue-prod
  STABLE_BUILD: 0

  # OSX specific variables
  DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
  MACOSX_DEPLOYMENT_TARGET: '10.11'

  # WIN32 specific variables
  PreferredToolArchitecture: X64

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
        build_type: [full]
        #os: [windows-latest, macOS-latest, ubuntu-latest]
        # exclude:
        #   - os: ubuntu-latest
        #     build_type: client
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
    - name: Report build number
      shell: bash
      run: |
        echo "Build number: $BUILD_NUMBER"
