name: Master CI Build

on: 
  push:
    branches:
      - gha-master-ci-dev
# FIXME: Change push target to "master" before merging into "master" branch.

env:
  APP_NAME: interface
  BUILD_TYPE: Release
  BUILD_NUMBER: ${{ github.run_number }}
  CI_BUILD: Github
  GIT_COMMIT: ${{ github.sha }}
  # VCPKG did not build well on OSX disabling HIFI_VCPKG_BOOTSTRAP, which invokes a download to a working version of vcpkg
  # HIFI_VCPKG_BOOTSTRAP: true
  RELEASE_TYPE: PRODUCTION
  RELEASE_NUMBER: ${{ github.run_number }}
  STABLE_BUILD: 0
  UPLOAD_BUCKET: athena-public

  # OSX-specific variables
  DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
  MACOSX_DEPLOYMENT_TARGET: '10.11'

  # WIN-specific variables
  PreferredToolArchitecture: X64

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-18.04]
        # build_type: [full, client]
        build_type: [full]
        include:
          - os: ubuntu-18.04
            build_type: full
            apt-dependencies: mesa-common-dev libegl1 libglvnd-dev libdouble-conversion1 libpulse0
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
    - name: Report build number
      shell: bash
      run: |
        echo "Build number: $BUILD_NUMBER"
    - name: Configure Build Environment 1
      shell: bash
      id: buildenv1
      run: |
        echo ::set-env name=UPLOAD_PREFIX::master
        echo ::set-env name=GIT_COMMIT_SHORT::`echo $GIT_COMMIT | cut -c1-7`
        echo ::set-env name=JOB_NAME::"build (${{matrix.os}}, ${{matrix.build_type}})"
        # Linux build variables
        if [[ "${{ matrix.os }}" = "ubuntu-"* ]]; then
          echo ::set-env name=PYTHON_EXEC::python3
          echo ::set-env name=INSTALLER_EXT::tgz
          echo ::set-env name=CMAKE_BUILD_EXTRA::"-- -j3"
          echo ::set-env name=CMAKE_EXTRA::"-DBUILD_TOOLS:BOOLEAN=FALSE -DHIFI_PYTHON_EXEC:FILEPATH=$(which python3)"
        fi
        # Mac build variables
        if [ "${{ matrix.os }}" = "macOS-latest" ]; then
          echo ::set-env name=PYTHON_EXEC::python3
          echo ::set-env name=ZIP_COMMAND::zip
          echo ::set-env name=ZIP_ARGS::-r
          echo ::set-env name=INSTALLER_EXT::dmg
          echo ::set-env name=CMAKE_EXTRA::"-DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED=OFF -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -G Xcode"
          echo "::set-output name=symbols_archive::${BUILD_NUMBER}-${{ matrix.build_type }}-mac-symbols.zip"
        fi
        # Windows build variables
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          echo ::set-env name=PYTHON_EXEC::python
          echo ::set-env name=ZIP_COMMAND::7z
          echo ::set-env name=ZIP_ARGS::a
          echo ::set-env name=INSTALLER_EXT::exe
          echo ::set-env name=CMAKE_EXTRA::"-A x64"
          echo "::set-env name=SYMBOL_REGEX::\(exe\|dll\|pdb\)"
          echo "::set-output name=symbols_archive::${BUILD_NUMBER}-${{ matrix.build_type }}-win-symbols.zip"
          # echo ::set-env name=HF_PFX_PASSPHRASE::${{secrets.pfx_key}}
          # echo "::set-env name=HF_PFX_FILE::${{runner.workspace}}\build\codesign.pfx"
        fi
    # Configuration is broken into two steps because you can't set an env var and also reference it in the same step
    - name: Configure Build Environment 2
      shell: bash
      run: |
        echo "${{ steps.buildenv1.outputs.symbols_archive }}"
        echo ::set-env name=ARTIFACT_PATTERN::Vircadia-Alpha-*.$INSTALLER_EXT
        # Build type variables
        if [ "${{ matrix.build_type }}" = "full" ]; then
          echo ::set-env name=CLIENT_ONLY::FALSE
          echo ::set-env name=INSTALLER::Vircadia-Alpha-$BUILD_NUMBER-$GIT_COMMIT_SHORT.$INSTALLER_EXT
        else
          echo ::set-env name=CLIENT_ONLY::TRUE
          echo ::set-env name=INSTALLER::Vircadia-Alpha-Interface-$BUILD_NUMBER-$GIT_COMMIT_SHORT.$INSTALLER_EXT
        fi
    - name: Clear Working Directory
      if: startsWith(matrix.os, 'windows')
      shell: bash
      working-directory: ${{runner.workspace}}
      run: rm -rf ./*
    - uses: actions/checkout@v1
      with: 
        submodules: true
        fetch-depth: 1
    - name: Install dependencies
      shell: bash
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        echo "Installing Python Modules:"
        pip3 install distro || exit 1
        echo "Updating apt repository index"
        sudo apt update || exit 1
        echo "Installing apt packages"
        sudo apt install -y ${{ matrix.apt-dependencies }} || exit 1
        echo "Installing boto3"
        # $PYTHON_EXEC -m pip install boto3 PyGithub
        # #######: Try pip3 command ...
        pip3 install boto3 PyGithub || exit 1
    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory "${{runner.workspace}}/build"
    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DVCPKG_BUILD_TYPE=release -DCLIENT_ONLY:BOOLEAN=$CLIENT_ONLY -DBYPASS_SIGNING:BOOLEAN=TRUE $CMAKE_EXTRA
    - name: Build Application
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target $APP_NAME $CMAKE_BUILD_EXTRA
    - name: Build Domain Server
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target domain-server $CMAKE_BUILD_EXTRA
    - name: Build Assignment Client
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target assignment-client $CMAKE_BUILD_EXTRA
    - name: Build Console
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target packaged-server-console $CMAKE_BUILD_EXTRA
    - name: Build Installer
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        echo "Retry code from https://unix.stackexchange.com/a/137639"
        function fail {
          echo $1 >&2
          exit 1
        }
        function retry {
          local n=1
          local max=5
          local delay=15
          while true; do
            "$@" && break || {
              if [[ $n -lt $max ]]; then
                ((n++))
                echo "Command failed. Attempt $n/$max:"
                sleep $delay;
              else
                fail "The command has failed after $n attempts."
              fi
            }
          done
        }
        retry cmake --build . --config $BUILD_TYPE --target package $CMAKE_BUILD_EXTRA
    #- name: Sign Installer (Windows)
    #  if: startsWith(matrix.os, 'windows')
    #  shell: powershell
    #  working-directory: C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64
    #  run: .\signtool.exe sign /fd sha256 /f ${{runner.workspace}}\build\codesign.pfx /p ${{secrets.pfx_key}} /tr http://sha256timestamp.ws.symantec.com/sha256/timestamp /td SHA256 ${{runner.workspace}}\build\${env:INSTALLER}
    - name: Output system stats
      if: ${{ always() }}
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        echo "Disk usage:"
        df -h
    - name: Output Installer Logs
      if: failure() && startsWith(matrix.os, 'windows')
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cat ./_CPack_Packages/win64/NSIS/NSISOutput.log
    - name: Upload Artifact
      if: matrix.os != 'ubuntu-latest'
      shell: bash
      working-directory: ${{runner.workspace}}/build	
      env:	
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}	
      run: $PYTHON_EXEC $GITHUB_WORKSPACE/tools/ci-scripts/upload.py 
    #- name: Archive Symbols
    #  if: (matrix.os == 'windows-latest') || (matrix.os == 'macOS-latest')
    #  working-directory: ${{runner.workspace}}
    #  shell: bash
    #  run: |
    #    SYMBOLS_TEMP="symbols-temp"
    #    mkdir $SYMBOLS_TEMP
    #    find "./build" \( -path '*/tools/gpu-frame-player/*' -or -path '*/interface/*' -or -path '*/plugins/*' \) -regex ".*\.$SYMBOL_REGEX" -exec cp -r {} $SYMBOLS_TEMP \;
    #    cd $SYMBOLS_TEMP
    #    $ZIP_COMMAND $ZIP_ARGS ../${{ steps.buildenv1.outputs.symbols_archive }} .
    #- name: Upload Symbols
    #  if: (matrix.os == 'windows-latest') || (matrix.os == 'macOS-latest')
    #  working-directory: ${{runner.workspace}}
    #  shell: bash
    #  run: |
    #    curl --data-binary @${{ steps.buildenv1.outputs.symbols_archive }} "$CMAKE_BACKTRACE_URL/post?format=symbols&token=$CMAKE_BACKTRACE_SYMBOLS_TOKEN&upload_file=${{steps.buildenv1.outputs.symbols_archive}}&tag=$BUILD_NUMBER"
    # - name: Debug List Symbols
    #   if: (matrix.os == 'windows-latest') || (matrix.os == 'macOS-latest')
    #   working-directory: ${{runner.workspace}}
    #   shell: bash
    #   run: |
    #     unzip -v "${{runner.workspace}}/${{ steps.buildenv1.outputs.symbols_archive }}"
    # - name: Debug Upload Symbols Artifact 
    #   if: (matrix.os == 'windows-latest') || (matrix.os == 'macOS-latest')
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: symbols
    #     path: ${{runner.workspace}}/${{ steps.buildenv1.outputs.symbols_archive }}
